[package]
name = "engine-crane"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "4.0.1"
parselnk = "0.1.0"
derive-new = "0.5"
serde_json = "1.0"
serde-hjson = { version = "0.9.1", default-features = false }
iced = "0.3"
zip = "0.5.13"
toml = "0.5.8"
csv = "1.1"
indexmap = "1.8.0"

[dependencies.rusqlite]
version = "0.26.0"
features = ["bundled"]
