[package]
name = "engine-crane"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "4.0.1"
parselnk = "0.1.0"
derive-new = "0.5"
serde_json = "1.0"
serde-hjson = { version = "0.9.1", default-features = false }
iced = "0.4.2"
zip = "0.6.2"
toml = "0.5.8"
csv = "1.1"
indexmap = "1.8.0"
fs_extra = "1.2.0"
walkdir = "2.3.2"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-appender = "0.2"
thiserror = "1.0"
itertools = "0.10"
sha2 = "0.10"
rfd = "0.10.0"

[dependencies.rusqlite]
version = "0.28.0"
features = ["bundled"]
