[package]
name = "automation"
version = "0.2.0-alpha"
edition = "2021"
authors = ["zephyrj <zephyrj@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
steam = { workspace = true }
utils = { workspace = true }
tracing =  { workspace = true }
sha2 = "0.10"

[target.'cfg(target_os = "windows")'.dependencies]
directories = "5.0.1"

[dependencies.rusqlite]
version = "0.29.0"
features = ["bundled"]
